### ISSUE TITLE
Ability to utilize DbUp GenerateUpgradeHtmlReport

### ISSUE THREAD

**Issue by clouddna-au** [asimeonov/DbUp.Downgrade#11]
**Describe the bug**
Would it be possible to utilize the DbUp GenerateUpgradeHtmlReport within DbUp.Downgrade 

**To Reproduce**
1. What is the `DbUp.Downgrade` version that you are using? 2.1.0
2. What is the `DbUp Script Provider` that you are using? 4.5.0
3. What is the issue that you have? Dont have ability to generate GenerateUpgradeHtmlReport 

**Expected behavior**
Ability like DbUp to generate report of scripts executed

**Comment by asimeonov** [comment]
Hey, I had a look over GenerateUpgradeHtmlReport functionality of DbUp. It is newly introduced in 4.5.0 I have missed it. In general it shows what scripts will be executed. In order to generate similar functionality there should be clear separation of the files for update and downgrade. DbUp is not always welcome to extensions in some aspects of the code and HtmlReport is one of them. I'm aiming to create another extension that will get both update and downgrade file paths and generate 2 reports based on the operation output. Will need around a week to prepare the solution and publish a new version.

Cheers

**Comment by asimeonov** [comment]
@clouddna-au I have noticed that in your ask you want to use only the DbUp GenerateUpgradeHtmlReport ability? This can be done without any updates from my side. After you create the downgrade engine `var upgrader = upgradeEngineBuilder.BuildWithDowngrade(true);` you can access the internal DbUp `UpgradeEngine` with `upgrader.UpgradeEngine.GenerateUpgradeHtmlReport("C:\\DeploymentLocation\\UpgradeReport.html");`

This will only generate report of scripts executed but not the one that are downgraded. I'm still working on the possibility to add this into the library. 

Cheers
